image: luxtorpeda/steam-runtime-amd64-beta:test-1

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - package

Build:
  stage: build
  script: ./build.sh

Package:
  stage: package
  script: ./package.sh
  artifacts:
    paths:
    - dist.tar.xz
    expire_in: 1 week
