image: luxtorpeda/steam-runtime-amd64-beta:test-1

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - package
  - publish

Build:
  stage: build
  script: ./build.sh
  artifacts:
    paths:
    - dist
    expire_in: 1 day

Package:
  stage: package
  script: ./package.sh
  artifacts:
    paths:
    - dist.tar.xz
    expire_in: 1 week

pages:
  stage: publish
  script:
  - mkdir public
  - sed "s|%DATE%|$(date)|" index.template > public/index.html
  - mv dist.tar.xz public
  artifacts:
    paths:
    - public
  only:
  - master
